export const provinces = [
  {
    title: "Toshkent shahri",
    region: "Toshkent",
  },
  {
    title: "Toshkent viloyati",
    region: "Toshkent",
  },
  {
    title: "Jizzax viloyati",
    region: "Toshkent",
  },
  {
    title: "Sirdaryo viloyati",
    region: "Toshkent",
  },
  {
    title: "Qoraqalpog'iston Respublikasi",
    region: "Nukus",
  },
  {
    title: "Xorazm viloyati",
    region: "Nukus",
  },
  {
    title: "Buxoro viloyati",
    region: "Nukus",
  },
  {
    title: "Samarqand viloyati",
    region: "Samarqand",
  },
  {
    title: "Qashqadaryo viloyati",
    region: "Samarqand",
  },
  {
    title: "Navoiy viloyati",
    region: "Samarqand",
  },
  {
    title: "Surxondaryo viloyati",
    region: "Samarqand",
  },
  {
    title: "Fargʻona viloyati",
    region: "Fargʻona",
  },
  {
    title: "Andijon viloyati",
    region: "Fargʻona",
  },
  {
    title: "Namangan viloyati",
    region: "Fargʻona",
  },
];

export const DISTRICTS = {
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Mirobod tumani",
    "Mirzo Ulug'bek tumani",
    "Olmazor tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Uchtepa tumani",
    "Yashnobod tumani",
    "Yakkasaroy tumani",
    "Yunusobod tumani",
  ],
  "Toshkent viloyati": [
    "Angren shahri",
    "Bekobod shahri",
    "Chirchiq shahri",
    "Nurafshon shahri",
    "Olmaliq shahri",
    "Ohangaron shahri",
    "Yangiyoʻl shahri",
    "Akkurgan tumani",
    "Bekobod tumani",
    "Boʻka tumani",
    "Boʻstonliq tumani",
    "Chinoz tumani",
    "Oʻrtachirchiq tumani",
    "Ohangaron tumani",
    "Parkent tumani",
    "Piskent tumani",
    "Qibray tumani",
    "Quyichirchiq tumani",
    "Toshkent tumani",
    "Yangiyo'l tumani",
    "Yuqorichirchiq tumani",
    "Zangiota tumani",
  ],
  "Jizzax viloyati": [
    "Jizzax shahri",
    "Arnasoy tumani",
    "Baxmal tumani",
    "Do'stlik tumani",
    "Forish tumani",
    "G'allaorol tumani",
    "Mirzacho'l tumani",
    "Paxtakor tumani",
    "Sharof Rashidov tumani",
    "Yangiobod tumani",
    "Zomin tumani",
    "Zafarobod tumani",
  ],
  "Sirdaryo viloyati": [
    "Guliston shahri",
    "Shirin shahri",
    "Yangiyer shahri",
    "Boyovut tumani",
    "Guliston tumani",
    "Mirzaobod tumani",
    "Oqoltin tumani",
    "Sardoba tumani",
    "Sayxunobod tumani",
    "Sirdaryo tumani",
    "Xovos tumani",
  ],
  "Qoraqalpog'iston Respublikasi": [
    "Nukus shahri",
    "Beruniy tumani",
    "Qonliko'l tumani",
    "Qorao'zak tumani",
    "Kegeyli tumani",
    "Mo'ynoq tumani",
    "Nukus tumani",
    "Taxtako'pir tumani",
    "To'rtko'l tumani",
    "Xo'jayli tumani",
    "Chimboy tumani",
    "Sho'manoy tumani",
    "Ellikqal'a tumani",
    "Amudaryo tumani",
    "Bo'zatov tumani",
  ],
  "Xorazm viloyati": [
    "Urganch shahri",
    "Xiva shahri",
    "Bog'ot tumani",
    "Gurlan tumani",
    "Xonqa tumani",
    "Xazorasp tumani",
    "Qo'shko'pir tumani",
    "Shovot tumani",
    "Urganch tumani",
    "Yangiariq tumani",
    "Yangibozor tumani",
  ],
  "Buxoro viloyati": [
    "Buxoro shahri",
    "Kogon shahri",
    "Buxoro tumani",
    "Vobkent tumani",
    "G'ijduvon tumani",
    "Jondor tumani",
    "Kogon tumani",
    "Olot tumani",
    "Peshku tumani",
    "Qorako'l tumani",
    "Qorovulbozor tumani",
    "Romitan tumani",
    "Shofirkon tumani",
  ],
  "Samarqand viloyati": [
    "Samarqand shahri",
    "Kattaqo'rg'on shahri",
    "Oqdaryo tumani",
    "Bulung'ur tumani",
    "Jomboy tumani",
    "Ishtixon tumani",
    "Kattaqo'rg'on tumani",
    "Narpay tumani",
    "Nurobod tumani",
    "Oqdaryo tumani",
    "Paxtachi tumani",
    "Payariq tumani",
    "Pastdarg'om tumani",
    "Samarqand tumani",
    "Toyloq tumani",
    "Urgut tumani",
  ],
  "Qashqadaryo viloyati": [
    "Qarshi shahri",
    "Shahrisabz shahri",
    "Chiroqchi tumani",
    "Dehqonobod tumani",
    "G'uzor tumani",
    "Kasbi tumani",
    "Kitob tumani",
    "Koson tumani",
    "Mirishkor tumani",
    "Muborak tumani",
    "Nishon tumani",
    "Qamashi tumani",
    "Qarshi tumani",
    "Shahrisabz tumani",
    "Yakkabog' tumani",
  ],
  "Navoiy viloyati": [
    "Navoiy shahri",
    "Zarafshon shahri",
    "Karmana tumani",
    "Konimex tumani",
    "Xatirchi tumani",
    "Navbahor tumani",
    "Nurota tumani",
    "Tomdi tumani",
    "Uchquduq tumani",
    "Qiziltepa tumani",
  ],
  "Surxondaryo viloyati": [
    "Termiz shahri",
    "Angor tumani",
    "Boysun tumani",
    "Denov tumani",
    "Jarqo'rg'on tumani",
    "Qiziriq tumani",
    "Qumqo'rg'on tumani",
    "Muzrobod tumani",
    "Oltinsoy tumani",
    "Sariosiyo tumani",
    "Sherobod tumani",
    "Sho'rchi tumani",
    "Termiz tumani",
    "Uzun tumani",
  ],
  "Fargʻona viloyati": [
    "Farg'ona shahri",
    "Marg'ilon shahri",
    "Qo'qon shahri",
    "Beshariq tumani",
    "Bog'dod tumani",
    "Buvayda tumani",
    "Dang'ara tumani",
    "Farg'ona tumani",
    "Furqat tumani",
    "O'zbekiston tumani",
    "Oltiariq tumani",
    "Qo'shtepa tumani",
    "Quva tumani",
    "Rishton tumani",
    "So'x tumani",
    "Toshloq tumani",
    "Uchko'prik tumani",
    "Yozyovon tumani",
  ],
  "Andijon viloyati": [
    "Andijon shahri",
    "Xonobod shahri",
    "Andijon tumani",
    "Asaka tumani",
    "Baliqchi tumani",
    "Bo'z tumani",
    "Buloqboshi tumani",
    "Jalaquduq tumani",
    "Izboskan tumani",
    "Qo'rg'ontepa tumani",
    "Marhamat tumani",
    "Oltinko'l tumani",
    "Paxtaobod tumani",
    "Ulug'nor tumani",
    "Xo'jaobod tumani",
  ],
  "Namangan viloyati": [
    "Namangan shahri",
    "Chortoq tumani",
    "Chust tumani",
    "Kosonsoy tumani",
    "Mingbuloq tumani",
    "Namangan tumani",
    "Norin tumani",
    "Pop tumani",
    "To'raqo'rg'on tumani",
    "Uchqo'rg'on tumani",
    "Uychi tumani",
    "Yangiqo'rg'on tumani",
  ],
};
